CREATE DATABASE INGEST;
CREATE DATABASE TRANSFORM;
CREATE DATABASE REPORTING;

CREATE ROLE DATA_ENGINEER LOGIN;
GRANT ALL ON DATABASE SANDBOX TO DATA_ENGINEER;
GRANT ALL ON DATABASE INGEST TO DATA_ENGINEER;
GRANT ALL ON DATABASE TRANSFORM TO DATA_ENGINEER;
GRANT ALL ON DATABASE REPORTING TO DATA_ENGINEER;
