#default airflow machine
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  
  config.vm.provider "virtualbox" do |vb|
    config.vm.hostname = "airflow-vm"
    vb.memory = "8192"
    vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ] #disable log files
  end 
  
  config.vm.network "public_network", ip: "192.168.1.200"
  config.vm.synced_folder "./shared/airflow_docker", "/opt/airflow", mount_options: ["dmode=777", "fmode=666"]
end



=begin
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
  end

  config.vm.network "private_network", ip: "192.168.33.10"

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y docker.io
    sudo usermod -aG docker vagrant

    sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    sudo chmod +x /usr/local/bin/docker-compose
  SHELL
end
=end

