version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: data_platform
    env_file:
      - ./postgres/config/variables.env
    #environment:
     # POSTGRES_DB: example-database
      #POSTGRES_USER: example-database
      #POSTGRES_PASSWORD: example-database-password
    ports:
      - "5432:5432"
    networks:
      - pg-network
    volumes:
      - pg-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pg-admin
    env_file:
      - ./pgadmin/config/variables.env
    #environment:
     # PGADMIN_DEFAULT_EMAIL: admin@example.com
      #PGADMIN_DEFAULT_PASSWORD: admin_password
    ports:
      - "5050:80"
    networks:
      - pg-network
    volumes:
      - ./pgadmin/config/servers.json:/pgadmin4/servers.json

networks:
  pg-network:

volumes:
  pg-data: